kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cte-csi-node-binding
subjects:
  - kind: ServiceAccount
    name: cte-csi-node
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cte-csi-node-ac
  apiGroup: rbac.authorization.k8s.io
