kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cte-csi-controller-binding
subjects:
  - kind: ServiceAccount
    name: cte-csi-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cte-csi-controller-ac
  apiGroup: rbac.authorization.k8s.io
